openapi: 3.0.1
info:
  description: "API defining resources and operations for configuring, reading and managing Device."
  version: "0.0.3"
  title: "Device Manager API"
servers:
  - url: "/api/v1"
tags:
  - name: Device
    description: Managing Device
paths:
  /devices:
    post:
      tags:
        - Device
      summary: Create ModbusTcp Device
      operationId: createDevice
      requestBody:
        description: ModbusTcp Device
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ModbusTcpDevice'
        required: true
      responses:
        201:
          description: The device has been created
          headers:
            ETag:
              schema:
                type: string
              description: ETag hash of the resource
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModbusTcpDevice'
        400:
          description: Invalid request.
        500:
          description: Internal Server Error.
components:
  schemas:
    ModbusTcpDevice:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          description: 设备名称.
          minLength: 1
          maxLength: 128
          pattern: '[\p{L}_0-9_\. ]+'
          example: 模拟modbustcp服务
        deviceCode:
          type: string
          description: 设备编码.
          maxLength: 256
          example: abcdfsdfe
        deviceType:
          type: string
          minLength: 1
          maxLength: 128
          pattern: '[a-z0-9]+'
          description: 设备类型.
          example: modbusTcp
        collectorCycle:
          type: integer
          description: 采集周期,单位为秒.
          default: 1
          example: 1
        variableInterval:
          type: integer
          description: 变量间隔.
          nullable: true
        adress:
          type: string
          description: IP地址.
        port:
          type: integer
          description: PORT端口.
        slave:
          type: integer
          description: SLAVE节点.
        memoryLayout:
          type: string
          enum:
            - ABCD
            - BADC
            - DCBA
            - CDAB
          description: 内存布局.
        positionAddress:
          type: integer
          description: 地址起始偏移量.
          nullable: true
        variables:
          type: array
          description: 变量组.
          items:
            type: object
            properties:
              name:
                type: string
                description: 变量名称
                example: A
              datatype:
                type: string
                description: 变量数据类型.
                enum:
                  - bool
                  - int16
                  - float32
                  - float64
                  - int32
                  - int64
                  - uint16
                example: int32
              address:
                type: integer
                description: 变量地址.(注意:地址起始寄存器数值为1!)
                example: 16
              bits:
                type: integer
                description: 位地址.(注意:地址起始位为1,数据类型为Bool类型时使用)
                nullable: true
              functionCode:
                type: integer
                description: 功能码
                example: 3
              rate:
                type: number
                description: 缩放比例
                example: 1.0
                nullable: true
              amount:
                type: integer
                description: 数量
                nullable: true
              defaultValue:
                type: number
                description: 默认值
                nullable: true