openapi: 3.0.1
info:
  description: "API defining resources and operations for configuring, reading and managing Device."
  version: "0.0.3"
  title: "Device Manager API"
servers:
  - url: "/api/v1"
tags:
  - name: Device
    description: Managing Device
paths:
  /devices:
    post:
      tags:
        - Device
      summary: Create Modbus Device
      operationId: createDevice
      requestBody:
        description: Modbus Device
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ModbusDevice'
        required: true
      responses:
        201:
          description: The device has been created
          headers:
            ETag:
              schema:
                type: string
              description: ETag hash of the resource
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModbusDevice'
        400:
          description: Invalid request.
        500:
          description: Internal Server Error.

    patch:
      tags:
        - Device
      summary: Update the Device
      description: Update the Device with the provided content.
      operationId: updateDeviceById
      parameters:
        - name: id
          in: path
          description: Unique identifier
          required: true
          schema:
            maxLength: 32
            minLength: 32
            pattern: '[0-9A-F]{32}'
            type: string
        - name: If-Match
          in: header
          description: Last known version to facilitate optimistic locking
          required: true
          schema:
            type: string
      requestBody:
        description: Modbus Device
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ModbusDevice'
        required: true
      responses:
        400:
          description: Invalid Request.
        404:
          description: Not Found.
        412:
          description: Precondition Failed.
        200:
          description: The device
          headers:
            ETag:
              schema:
                type: string
              description: ETag hash of the resource
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModbusDevice'
components:
  schemas:
    ModbusDevice:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          description: 设备名称.
          minLength: 1
          maxLength: 128
          pattern: '[\p{L}_0-9_\. ]+'
          example: 模拟modbus服务
        deviceCode:
          type: string
          description: 设备编码.
          maxLength: 256
          example: abcdfsdfe
        deviceType:
          type: string
          default: modbus
          description: 设备类型.
        deviceModel:
          type: string
          enum:
            - modbusTcp
            - modbusRtu
            - modbusRtuOverTcp
          description: 设备型号.
          example: modbusTcp
        collectorCycle:
          type: integer
          description: 采集周期,单位为秒.
          default: 1
          example: 1
        variableInterval:
          type: integer
          description: 变量间隔.
          nullable: true
        address:
          type: object
          properties:
            location:
              type: string
              description: IP地址/串口地址.
            option:
              type: object
              description: 其他参数
              properties:
                port:
                  type: integer
                  description: IP地址的端口.
                  example: 502
                baudRate:
                  type: integer
                  description: 波特率.
                  enum:
                    - 1200
                    - 2400
                    - 4800
                    - 9600
                    - 19200
                    - 38400
                    - 57600
                    - 115200
                  example: 9600
                DataBits:
                  type: integer
                  description: 数据位.
                  enum:
                    - 5
                    - 6
                    - 7
                    - 8
                  example: 502
                parity:
                  type: string
                  description: 校验位.
                  enum:
                    - noParity
                    - oddParity
                    - evenParity
                stopBits:
                  type: string
                  description: 停止位.
                  enum:
                    - 1
                    - 1.5
                    - 2
          description: Modbus服务器参数.
        slave:
          type: integer
          description: SLAVE节点.
        memoryLayout:
          type: string
          enum:
            - ABCD
            - BADC
            - DCBA
            - CDAB
          description: 内存布局.
        positionAddress:
          type: integer
          description: 地址起始偏移量.
          nullable: true
        topic:
          type: string
          description: MQTT消息队列Topic.
          nullable: false
        variables:
          type: array
          description: 变量组.
          items:
            type: object
            properties:
              name:
                type: string
                description: 变量名称.
                example: A
              datatype:
                type: string
                description: 变量数据类型.
                enum:
                  - string
                  - number
                  - float32
                  - float64
                  - int32
                  - int64
                  - uint16
                example: int32
              address:
                type: integer
                description: 变量地址.(注意:地址起始寄存器数值为0!)
                example: 16
              bits:
                type: integer
                description: 位地址.(注意:地址起始位为0,数据类型为Bool类型时使用)
                nullable: true
              functionCode:
                type: integer
                description: 功能码
                example: 3
              rate:
                type: number
                description: 缩放比例
                example: 1.0
                nullable: true
              amount:
                type: integer
                description: 数量
                nullable: true
              defaultValue:
                type: number
                description: 默认值
                nullable: true
              accessMode:
                type: string
                description: 读写属性
                enum:
                  - r
                  - rw
                example: rw